### ISSUE TITLE
Readme: Details on how to view a video on local system

### ISSUE THREAD

**Issue by nav-avo** [vivictorg/vivict#25]
If there are videos on my system at `/home/user/videos/`, I would need to know how to play them using Vivict. The current instructions in the readme do mention how to play videos on `localhost`, but require more details to mention how to take videos from the filesystem by specifying a folder path.

**Comment by grusell** [comment]
To open a local file, you need to click the 'open file' icon, marked in green in the attached picture.
![vivict_open_file](https://user-images.githubusercontent.com/3780796/208173312-5db0ed41-e601-4dc0-95f0-1d825a206690.png)

**Comment by nav-avo** [comment]
Thank you. I'd encourage adding this information to the readme too. 
Vivict is an amazing software. Even more amazing, is the fact that you came up with this idea of displaying two videos pixels in this flexible manner. Simply brilliant!
