### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by chrizilla** [vivictorg/vivict#28]
On https://vivictorg.github.io/vivict/ I added two videos:
- mkv video in the left pane
- mp4 video in the right pane

I click on space bar, but nothing happens. Neither of the videos play.
I just see an empty black screen :/

**Comment by grusell** [comment]
Video playback is limited by what the browser supports, and I don't think mkv playback is supported by any browser. Does the mp4 playback ok in vivict without the mkv? There could potentially also be issues with codec not being supported by browser.

Which browser are you using and what codec are the videos using?

**Comment by chrizilla** [comment]
Hi @grusell Many thanks for your help! I am using an up2date Firefox.

It seems you have identified the problem correctly. In my tests, there is a 100% correlation:
- If the video file is playable in Firefox, I can indeed play it in vivict (sorry that I missed this).
- If the video file is not playable in Firefox, I can't play it in vivict either.

MKV files don't seem to play in my Firefox (that's a pity, because I remux all my videos to MKV).
MP4 files: some play in Firefox (and thus in vivict), some don't. Probably depends on the codec.

So what can I do ?
Is there any way to "teach" Firefox how to play the files ? Maybe with an addon or something ?
Any workaround ?

**Comment by chrizilla** [comment]
> Is there any way to "teach" Firefox how to play the files ? Maybe with an addon or something ?

I found two Firefox addons:
https://addons.mozilla.org/en-US/firefox/addon/the-media-player/
https://addons.mozilla.org/en-US/firefox/addon/local-media-player-for-you/

Is this absolutely useless or do you think it might be worth trying ?

There also was a [VLC plugin for Firefox back in 2009](https://superuser.com/a/52624/961501) and [2014](https://stackoverflow.com/questions/21192713/how-to-playback-mkv-video-in-web-browser), but I assume it is deprecated now.

**Comment by grusell** [comment]
Hmm I see. I will ihave to investigate this.

**Comment by chrizilla** [comment]
Anything I can do to help investigate this ?

I managed to add mp4 files via the document icon. But I am unsuccessful so far in adding webm files (despite being playable in the browser).

It would be helpful to at least get any sort or error message, because right now nothing happens (hence the issue title).

**Comment by grusell** [comment]
Added support for webm files. There was a silent error when trying to parse the metadata that causes the file to not be loaded. Metadata for webm files is not shown but they can be played.

**Comment by chrizilla** [comment]
That's awesome! Many thanks for the quick fix! 👍 

Could you issue an error in the future whenever a non-compatible file is selected ?
Would be better than doing nothing and leaving the user wonder what happens ...

Have you seen [my comment above](https://github.com/vivictorg/vivict/issues/28#issuecomment-1495122162) and do you have an idea if adding the VLC plugin or other Firefox addons would make all files open in vivict too if they are playable in the browser? It seems you said that files that Firefox cannot play can therefore not be opened in vivict. But is the reverse true, i.e. can all vivict open all files that play in the browser? If yes, if an addon/plugin makes a previously unplayable file now playable, does this mean that it also becomes automatically available in vivict? I mean is there a 1:1 relationship, meaning all (100%) files playable in the browser (regardless of playability out of the box or with addon-help) can be opened in vivict ?

**Comment by grusell** [comment]
> That's awesome! Many thanks for the quick fix! +1
No prob!
> Could you issue an error in the future whenever a non-compatible file is selected ? Would be better than doing nothing and leaving the user wonder what happens ...
> 
I agree that would make sense, there is actually an issue for that: https://github.com/vivictorg/vivict/issues/21 . I don't see me having the time to fix that in the near future though.

> Have you seen [my comment above](https://github.com/vivictorg/vivict/issues/28#issuecomment-1495122162) and do you have an idea if adding the VLC plugin or other Firefox addons would make all files open in vivict too if they are playable in the browser? It seems you said that files that Firefox cannot play can therefore not be opened in vivict. But is the reverse true, i.e. can all vivict open all files that play in the browser? If yes, if an addon/plugin makes a previously unplayable file now playable, does this mean that it also becomes automatically available in vivict? I mean is there a 1:1 relationship, meaning all (100%) files playable in the browser (regardless of playability out of the box or with addon-help) can be opened in vivict ?
Vivivct should be able to play any files that can play natively in the browser. I'm not sure if a plugin could make vivict able to play a file without any change to the vivict source code.

**Comment by chrizilla** [comment]
> I agree that would make sense, there is actually an issue for that: #21 

👍 

> Vivivct should be able to play any files that can play natively in the browser.
> I'm not sure if a plugin could make vivict able to play a file without any change to the vivict source code.

Ok, I'll try to experiment and will let you know if I can come to any solid conclusion about that. Thank you.
